version: '3.0'
services:
  database:

    image: mysql:5.6
    container_name: database
    networks:
      - wpnet
    volumes:
      - "databasedata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpress@123

  wordpress:  

    image: wordpress
    container_name: wordpress
    restart: always
    ports: 
      - 8080:8888
    networks:
      - wpnet
    volumes:
      - wordpressdata:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpress@123
      WORDPRESS_DB_NAME: wordpress


networks:
  wpnet:

volumes:
  wordpressdata:
  databasedata:

       
           