version: "3"

services:
  database:

    image: mysql:5.6
    container_name: database
    networks:
      - wp_net
    volumes:
      - "database_data:/var/lib/mysql"
    enviornment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpress@123

  wordpress:  

    image: wordpress
    container_name: wordpress
    restart: always
    ports: 
      - 8080:80
    network:
      - wp_net
    volumes:
      - wordpress_data:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpress@123
      WORDPRESS_DB_NAME: wordpress


network:
  wp_net:

volumes:
  wordpress_data:
  database_data:

       
           